sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Hi1JOEiCxwk8CZj9NYEm8rEFhJKl6u+4kQrWoZvJ/YB+tFM08dJsb8wgVLsTtOuNkGptrfTeam1EZVfGC/6nnXuONPbZ0SpkaRMsWeRSLG79TqT5QefMOLd1pIfKh+Fhm+1TYBg9zMJ4HNDtP2Xr8Bcq5YpMSw3q+EgvQO+TX6xQ3d+r41OEQIZTvVvtV5aXbUnnrOaGf9477Z+U4i7bkRecRELmoP+KlSoOfjOl4s/W0BDrxG4/N4n2/oslFFjtdRL0cJN/mtsF7NJtwlE1gzQoakkCjgm1c7rAIrvRuf8DNKceLe4hL//bbS0h8mGQrLnRvu4JTLvWvQn2Xyeku4GM80PhJ89mh3H3Lke83eppIAHDsPwSD99kOodqvbEuNdyRbxHV/W1rbmMOUILzjPC4m6A3tY5L8Yvo2JxAlTCLJgVueru3qh3oXwHPZVquJDLk8/A3FNP7ou61zDjPOPccRHdSdwMYKPWs0ZbBEXCazrDHxUKU591itN3tagCuX8ETWMEWVSdNt9ELtONqwyUbDL5ZPxwx3Qf7xuAqnPjGL3CuXFdubHMTNGCBqjxx4v/hWjVtGkqo9mGHDGiXwsktXfR7huE/vkhRarkUl9HF7BswylRIYNUpJNl5XqMmzMNqt91NnrIvasTDYVW/HXA+EXqR5DAnBzCxdgKr1CM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Cell-of-Self-Knowledge---seven-early-English-mystical-treatises-printed-by-Henry-Pepwell-i__4544
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy